### ISSUE TITLE
Missing teamSize and attacksPerMember fields

### ISSUE THREAD

**Issue by Lycoon** [devhl-labs/Clash-of-Clans-Swagger#1]
The `swagger.yaml` file lacks of `teamSize` and `attacksPerMember` fields for `ClanWar`

https://github.com/devhl-labs/Clash-of-Clans-Swagger/blob/ae6b3da837998930c88de99e50ae7789dbaf095a/swagger.yml#L767-L792

Here's what's given by Clash of Clans API:

![image](https://user-images.githubusercontent.com/1346471/146941710-3b8d2979-a2b8-4e28-982c-e732a8804476.png)

**Comment by erwanvivien** [comment]
It's very unfortunate, I believe the swagger is not totally up-to-date

**Comment by devhl-labs** [comment]
I can add those next week, or you can do a pr.

**Comment by devhl-labs** [comment]
Added with de346cd5860cca2a3d8f29bb70b70eafa9f3ea5b
